services:
  socks5-proxy:
    image: 'ghcr.io/ariadata/go-socks5-proxy:latest'
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    container_name: go-socks5-proxy
    restart: unless-stopped
    ports:
      - '${DC_PROXY_PORT:-1080}:1080'
    command: ["./socks5-server", "--host", "0.0.0.0", "--port", "1081" , "--users", "/app/users.conf"]
    volumes:
      - ./users.conf:/app/users.conf
